### PR TITLE
Updated alternate icons and added new ones

### PR DESCRIPTION
**Pull request by XusBadia**

### CODE REVIEW

**Comment by balloob** [comment]
I don't really see why we would need these icons. They are not used by anything nor do I think that all the colors would ever be useful to have.

**Comment by XusBadia** [comment]
I think its a matter of customization. People use different themes with different colors, so maybe changing the home screen icon is something that would appeal to them; I know it does for me and some of my friends. They are currently used in the iOS app (and I could make the Android counterparts if you want me to).

If you prefer not to have them to stick with the “official” blue, I totally understand, though.

**Comment by balloob** [comment]
`Alternates/black.png` has an incorrect shadow on the chimney.

Yeah, I don't think that we should have the alternates in this repo. This repo already kinda lost its goal of being a single place where we store our logo. Let's just keep them in the iOS app?

**Comment by XusBadia** [comment]
I made that shadow to make it look different, but now that I look back at it, you are probably right on that, I'll change it to the default shadow.

I made the pull request because @robbiet480 asked for it in the Home Assistant for iOS repo asked for it. If you think they shouldn't be here, that's fine.

**Comment by balloob** [comment]
Let's close this. I think we should remove all alternates from this repo and keep them in iOS repo. @robbiet480 what do you think ?

**Comment by robbiet480** [comment]
Not a problem, I only asked for them to be added here so others could one day benefit maybe. Closing this and will remove the older alternates from this repo. Sorry for the runaround both of you, especially @XusBadia, I should've coordinated with @balloob first.

**Comment by robbiet480** [comment]
Removed old ones at 1ee81ec321f1e5f7fcd0f0c844ba59ad7ab0a56b

**Comment by TheZoker** [comment]
I think one usecase would be, if people want to use these icons for making their custom merch or something. Like if someone wants a t-shirt with the red icon on it

**Comment by XusBadia** [comment]
> Not a problem, I only asked for them to be added here so others could one day benefit maybe. Closing this and will remove the older alternates from this repo. Sorry for the runaround both of you, especially @XusBadia, I should've coordinated with @balloob first.

No problem at all, @robbiet480 I'm just glad I can contribute.

**Pull request closed without merging**
