### PR TITLE
Add plottable logo

### PR DESCRIPTION
**Pull request by vidschofelix**
Based on the responsive logo, i created a plottable/cuttable version reduced to the minimum. Tree and baseform are merged, so there will be no cut between the tree and the outer form.

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @vidschofelix, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;assets#17).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by balloob** [comment]
CC @matthiasdebaat

**Comment by matthiasdebaat** [comment]
Awesome @vidschofelix! I think a plottable logo would be a great addition to our [set](https://github.com/home-assistant/assets/tree/master/logo). 

I will update our other logos based on this svg. For example [assets/logo/logo.svg](https://github.com/home-assistant/assets/blob/master/logo/logo.svg) and [assets/logo/logo.png](https://github.com/home-assistant/assets/blob/master/logo/logo.png) with this rounded border and with an extra shadow.

**Comment by matthiasdebaat** [comment]
Cleaned up svg code and added path id's

**Review by matthiasdebaat — CHANGES_REQUESTED** [review]
_Edit: can't get GitHub get show my change suggestions_

**Comment by balloob** [comment]
Going to close this PR as this logo is no longer used.

**Pull request closed without merging**
