### PR TITLE
Adds a PNG image to serve as template

### PR DESCRIPTION
**Pull request by dgomes**
@frenck as discussed on discord

### CODE REVIEW

**Comment by bramkragten** [comment]
Can we give it a slight rounded corner? To match the rounding of the cards in Figma? <https://www.figma.com/file/4LZqQZRynDZGTgA2rN35Te/Home-Assistant-config-mockup?node-id=0%3A1>

**Comment by dgomes** [comment]
This is to be used as a template, no problems in changing it afterwards to round the corners

**Comment by frenck** [comment]
Well, if we ask people to add rounded corners afterward, it will not happen in many cases. If it is in now, the only thing one would have to do: Slap on an MDI icon...

**Comment by dgomes** [comment]
I was thinking more in the likes of Android app icons that automatically round the corners...

I will update the PR with a rounded corners. Do the Sigma round corners come with a specification of the round amount ?

**Comment by bramkragten** [comment]
Normally I would say 8px, but since this image will be scaled I think it should be in proportion of the image size. Maybe 32px?

**Comment by dgomes** [comment]
Updated

**Comment by frenck** [comment]
Small discussion going on, but you are right @dgomes. Let's keep it square and solve it elsewhere.

Let's revert that last commit and merge it after that 👍

**Comment by dgomes** [comment]
Don't have merge permissions to this repo

**Review by frenck — APPROVED** [review]
Thanks, @dgomes! 👍

**Pull request merged**
